fix(block_storage): handle BS volume deletion in instance update
Previously, if a block storage volume was deleted and detached at the
same time, the detachment attempt during instance update would fail
with:
```
Error: failed to detach block storage: DetachBlockStorageVolume: http response: Not Found: Blockstorage Volume not found
```

This is because the BS volume was already deleted in `ResourceVolume.Delete`.

The error was harmless since the volume would be deleted and detached
anyways, and a subsequent `apply` would succeed, but it interrupted the
process, and would cause confusion.

The fix simply checks for `v3.ErrNotFound`, allowing the instance update
to continue.

Fixes internal support ticket 1167622