chore: upgrade `golang.org/x/net` and related deps (#540)
# Description
<!--
* Prefix: the title with the component name being changed. Add a short
and self describing sentence to ease the review
* Please add a few lines providing context and describing the change
* Please self comment changes whenever applicable to help with the
review process
* Please keep the checklist as part of the PR. Tick what applies to this
change.
-->

This resolves a [recent vulnerabilty][1] [reported by `govulncheck`][2]:

```
Vulnerability #1: GO-2026-5026
    Invoking failure to reject ASCII-only Punycode-encoded labels in
    golang.org/x/net/idna
  More info: https://pkg.go.dev/vuln/GO-2026-5026
  Module: golang.org/x/net
    Found in: golang.org/x/net@v0.52.0
    Fixed in: golang.org/x/net@v0.55.0
    Example traces found:
Error:       #1: main.go:58:23: terraform.main calls tf6server.Serve, which eventually calls idna.Profile.ToASCII
Error:       #2: pkg/resources/block_storage/resource_volume.go:606:15: block_storage.ResourceVolume.ImportState calls fmt.Sprintf, which eventually calls idna.Profile.ToUnicode
Error:       #3: exoscale/resource_exoscale_domain.go:23:32: exoscale.domainNameToUnicode calls idna.ToUnicode
```

I glanced at the vendor diff, and don't expect any regressions, but we
should run the full acceptance suite to be safe.

Sidenote: we should switch to [our `govulncheck` fork][3] so that we can
easily exclude unrelated vulns. This one is exposed to users, so it
shouldn't be ignored.

[1]: https://pkg.go.dev/vuln/GO-2026-5026

[2]:
https://github.com/exoscale/terraform-provider-exoscale/actions/runs/26811063038/job/79040851229?pr=539

[3]: https://github.com/exoscale/govulncheck

## Checklist
(For exoscale contributors)

* [x] Changelog updated (under *Unreleased* block)
* [ ] Acceptance tests OK
* [ ] For a new resource, datasource or new attributes: acceptance test
added/updated

## Testing

`make test` passes.