test: skip acceptance tests unless TF_ACC is set
Running `make test` still runs some acceptance tests, which fail if API
credentials aren't set in the environment. E.g.:

```
--- FAIL: TestAccResourceSKSClusterSKSClusterWithAudit (0.00s)
    resource_exoscale_sks_cluster_test.go:809: unable to initialize Exoscale client: missing or incomplete API credentials
```

This is because they call `testGetSKSClusterVersions`, which attempts to
initialize an API client. I tried moving the call inside
`resource.Test`, which would skip them because the same `TF_ACC` check
is done inside, but some of our tests use the result of
`testGetSKSClusterVersions` to set the `resource.TestStep.Config`
string, so we'd need to lazy eval it somehow, which would require more
complex changes than this.

Also, I noticed that `make test-acc` runs `go test -tags=testacc`[1],
but that build tag is not used anywhere, so we could remove this.

An alternative way to run acceptance tests could be with `-run
'TestAcc.*'`, since we use a consistent naming scheme from what I've
seen.

[1]: https://github.com/exoscale/terraform-provider-exoscale/blob/963f0275a423d7edfdad376ac204a09b818fb5ee/Makefile#L54